/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */
plugins {
    kotlin("jvm") version "2.0.10" // Kotlin version
    kotlin("plugin.spring") version "2.0.10" // Kotlin version
    id("org.springframework.boot") version "3.5.5"
    id("io.spring.dependency-management") version "1.1.7" // from Gradle Plugin Portal
}

java {
    sourceCompatibility = JavaVersion.VERSION_21 // Java Versionを指定
}

repositories {
    mavenCentral()
}

// Spring Boot Webアプリに必要な依存関係を追加
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") // SpringbootWebフレームワーク
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf") // Template Engine
    implementation("org.springframework.boot:spring-boot-devtools")
}
