/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */
plugins {
    kotlin("jvm") // Kotlin version
    kotlin("plugin.spring") // Kotlin version
    id("org.springframework.boot")
    id("io.spring.dependency-management") // from Gradle Plugin Portal
}

java {
    sourceCompatibility = JavaVersion.VERSION_17 // Java Versionを指定
}

// Spring Boot Webアプリに必要な依存関係を追加
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") // SpringbootWebフレームワーク
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf") // Template Engine
    implementation("org.springframework.boot:spring-boot-devtools")

    // 開発環境用: H2データベースドライバ
    runtimeOnly("com.h2database:h2")
    implementation(project(":modules:stock")) // stockを有効にする
}

// マルチモジュール構成の為、class mainを指定する必要がある
tasks.bootRun {
    mainClass.set("com.example.ApplicationKt") 
}
