/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */
plugins {
    kotlin("jvm") // Kotlin version
    kotlin("plugin.spring") // Kotlin version
    id("org.springframework.boot") // implementation springframework.bootを使用しているため
    id("io.spring.dependency-management")  // 親子モジュールで必要
}

java {
    sourceCompatibility = JavaVersion.VERSION_17 // Java Versionを指定
}

// Spring Boot Webアプリに必要な依存関係を追加
dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web") // SpringbootWebフレームワーク
    implementation("org.springframework.boot:spring-boot-starter-thymeleaf") // Template Engine

    // 開発環境のみdevtoolを有効に
    developmentOnly("org.springframework.boot:spring-boot-devtools")

    // データベース設定
    implementation("org.springframework.boot:spring-boot-starter-data-jpa") // webでも使う(DB(H2)が有効にならないので追加する必要あり)
    // 開発環境用: H2データベースドライバ
    runtimeOnly("com.h2database:h2")

     // webからsubmodule stockの機能を利用する為、読み込む
    implementation(project(":modules:stock"))
}

// マルチモジュール構成の為、class mainを指定する必要がある
tasks.bootRun {
    mainClass.set("com.example.ApplicationKt") 
}
