/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 */
plugins {
    kotlin("jvm") // Kotlin version
    kotlin("plugin.spring") // Kotlin version
    kotlin("plugin.jpa") // デフォルトコンストラクタを設定することを回避する
    id("io.spring.dependency-management") // 親子モジュールで必要
    id("org.springframework.boot") // implementationでspringframework.bootを使っている為、指定
}

java {
    sourceCompatibility = JavaVersion.VERSION_17 // Java Versionを指定
}

// Spring Boot Webアプリに必要な依存関係を追加
dependencies {
    // Webアプリケーション、JPAに必要な基本的な依存関係
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")

    // KotlinでEntityを使う場合に推奨される依存関係
    implementation("org.jetbrains.kotlin:kotlin-reflect")
    implementation("org.springframework.boot:spring-boot-starter-validation") // バリデーション
}
